# Используем официальный образ Python
FROM python:3.11-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем pyproject.toml и зависимости
COPY pyproject.toml ./
COPY categorizedinventory/ categorizedinventory/

# Устанавливаем зависимости
RUN pip install --upgrade pip && \
    pip install .

# Копируем всё остальное
COPY . .

# Указываем порт
EXPOSE 5000

# Команда запуска
CMD ["python", "main.py"]